/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimulatorRouteImport } from './routes/_app/simulator'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRecommendationsRouteImport } from './routes/_app/recommendations'
import { Route as AppPricingRouteImport } from './routes/_app/pricing'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoachRouteImport } from './routes/_app/coach'
import { Route as AppChallengesRouteImport } from './routes/_app/challenges'
import { Route as AppBudgetRouteImport } from './routes/_app/budget'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAdvisorRouteImport } from './routes/_app/advisor'
import { Route as AppAdvisorRiskRadarRouteImport } from './routes/_app/advisor.risk-radar'
import { Route as AppAdvisorReportsRouteImport } from './routes/_app/advisor.reports'
import { Route as AppAdvisorRecommendationsRouteImport } from './routes/_app/advisor.recommendations'
import { Route as AppAdvisorInvitationsRouteImport } from './routes/_app/advisor.invitations'
import { Route as AppAdvisorClientsRouteImport } from './routes/_app/advisor.clients'
import { Route as AppAdvisorClientIdRouteImport } from './routes/_app/advisor/client.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRiskRadarRoute = AppAdvisorRiskRadarRouteImport.update({
  id: '/risk-radar',
  path: '/risk-radar',
  getParentRoute: () => AppAdvisorRoute,
} as any)
const AppAdvisorReportsRoute = AppAdvisorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdvisorRoute,
} as any)
const AppAdvisorRecommendationsRoute =
  AppAdvisorRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AppAdvisorRoute,
  } as any)
const AppAdvisorInvitationsRoute = AppAdvisorInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppAdvisorRoute,
} as any)
const AppAdvisorClientsRoute = AppAdvisorClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppAdvisorRoute,
} as any)
const AppAdvisorClientIdRoute = AppAdvisorClientIdRouteImport.update({
  id: '/client/$id',
  path: '/client/$id',
  getParentRoute: () => AppAdvisorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/advisor': typeof AppAdvisorRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/budget': typeof AppBudgetRoute
  '/challenges': typeof AppChallengesRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/insights': typeof AppInsightsRoute
  '/notifications': typeof AppNotificationsRoute
  '/pricing': typeof AppPricingRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/settings': typeof AppSettingsRoute
  '/simulator': typeof AppSimulatorRoute
  '/advisor/clients': typeof AppAdvisorClientsRoute
  '/advisor/invitations': typeof AppAdvisorInvitationsRoute
  '/advisor/recommendations': typeof AppAdvisorRecommendationsRoute
  '/advisor/reports': typeof AppAdvisorReportsRoute
  '/advisor/risk-radar': typeof AppAdvisorRiskRadarRoute
  '/advisor/client/$id': typeof AppAdvisorClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/advisor': typeof AppAdvisorRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/budget': typeof AppBudgetRoute
  '/challenges': typeof AppChallengesRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/insights': typeof AppInsightsRoute
  '/notifications': typeof AppNotificationsRoute
  '/pricing': typeof AppPricingRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/settings': typeof AppSettingsRoute
  '/simulator': typeof AppSimulatorRoute
  '/advisor/clients': typeof AppAdvisorClientsRoute
  '/advisor/invitations': typeof AppAdvisorInvitationsRoute
  '/advisor/recommendations': typeof AppAdvisorRecommendationsRoute
  '/advisor/reports': typeof AppAdvisorReportsRoute
  '/advisor/risk-radar': typeof AppAdvisorRiskRadarRoute
  '/advisor/client/$id': typeof AppAdvisorClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/advisor': typeof AppAdvisorRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/budget': typeof AppBudgetRoute
  '/_app/challenges': typeof AppChallengesRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/simulator': typeof AppSimulatorRoute
  '/_app/advisor/clients': typeof AppAdvisorClientsRoute
  '/_app/advisor/invitations': typeof AppAdvisorInvitationsRoute
  '/_app/advisor/recommendations': typeof AppAdvisorRecommendationsRoute
  '/_app/advisor/reports': typeof AppAdvisorReportsRoute
  '/_app/advisor/risk-radar': typeof AppAdvisorRiskRadarRoute
  '/_app/advisor/client/$id': typeof AppAdvisorClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/advisor'
    | '/analytics'
    | '/budget'
    | '/challenges'
    | '/coach'
    | '/dashboard'
    | '/expenses'
    | '/insights'
    | '/notifications'
    | '/pricing'
    | '/recommendations'
    | '/settings'
    | '/simulator'
    | '/advisor/clients'
    | '/advisor/invitations'
    | '/advisor/recommendations'
    | '/advisor/reports'
    | '/advisor/risk-radar'
    | '/advisor/client/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/advisor'
    | '/analytics'
    | '/budget'
    | '/challenges'
    | '/coach'
    | '/dashboard'
    | '/expenses'
    | '/insights'
    | '/notifications'
    | '/pricing'
    | '/recommendations'
    | '/settings'
    | '/simulator'
    | '/advisor/clients'
    | '/advisor/invitations'
    | '/advisor/recommendations'
    | '/advisor/reports'
    | '/advisor/risk-radar'
    | '/advisor/client/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/advisor'
    | '/_app/analytics'
    | '/_app/budget'
    | '/_app/challenges'
    | '/_app/coach'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/insights'
    | '/_app/notifications'
    | '/_app/pricing'
    | '/_app/recommendations'
    | '/_app/settings'
    | '/_app/simulator'
    | '/_app/advisor/clients'
    | '/_app/advisor/invitations'
    | '/_app/advisor/recommendations'
    | '/_app/advisor/reports'
    | '/_app/advisor/risk-radar'
    | '/_app/advisor/client/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simulator': {
      id: '/_app/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenges': {
      id: '/_app/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisor': {
      id: '/_app/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisor/risk-radar': {
      id: '/_app/advisor/risk-radar'
      path: '/risk-radar'
      fullPath: '/advisor/risk-radar'
      preLoaderRoute: typeof AppAdvisorRiskRadarRouteImport
      parentRoute: typeof AppAdvisorRoute
    }
    '/_app/advisor/reports': {
      id: '/_app/advisor/reports'
      path: '/reports'
      fullPath: '/advisor/reports'
      preLoaderRoute: typeof AppAdvisorReportsRouteImport
      parentRoute: typeof AppAdvisorRoute
    }
    '/_app/advisor/recommendations': {
      id: '/_app/advisor/recommendations'
      path: '/recommendations'
      fullPath: '/advisor/recommendations'
      preLoaderRoute: typeof AppAdvisorRecommendationsRouteImport
      parentRoute: typeof AppAdvisorRoute
    }
    '/_app/advisor/invitations': {
      id: '/_app/advisor/invitations'
      path: '/invitations'
      fullPath: '/advisor/invitations'
      preLoaderRoute: typeof AppAdvisorInvitationsRouteImport
      parentRoute: typeof AppAdvisorRoute
    }
    '/_app/advisor/clients': {
      id: '/_app/advisor/clients'
      path: '/clients'
      fullPath: '/advisor/clients'
      preLoaderRoute: typeof AppAdvisorClientsRouteImport
      parentRoute: typeof AppAdvisorRoute
    }
    '/_app/advisor/client/$id': {
      id: '/_app/advisor/client/$id'
      path: '/client/$id'
      fullPath: '/advisor/client/$id'
      preLoaderRoute: typeof AppAdvisorClientIdRouteImport
      parentRoute: typeof AppAdvisorRoute
    }
  }
}

interface AppAdvisorRouteChildren {
  AppAdvisorClientsRoute: typeof AppAdvisorClientsRoute
  AppAdvisorInvitationsRoute: typeof AppAdvisorInvitationsRoute
  AppAdvisorRecommendationsRoute: typeof AppAdvisorRecommendationsRoute
  AppAdvisorReportsRoute: typeof AppAdvisorReportsRoute
  AppAdvisorRiskRadarRoute: typeof AppAdvisorRiskRadarRoute
  AppAdvisorClientIdRoute: typeof AppAdvisorClientIdRoute
}

const AppAdvisorRouteChildren: AppAdvisorRouteChildren = {
  AppAdvisorClientsRoute: AppAdvisorClientsRoute,
  AppAdvisorInvitationsRoute: AppAdvisorInvitationsRoute,
  AppAdvisorRecommendationsRoute: AppAdvisorRecommendationsRoute,
  AppAdvisorReportsRoute: AppAdvisorReportsRoute,
  AppAdvisorRiskRadarRoute: AppAdvisorRiskRadarRoute,
  AppAdvisorClientIdRoute: AppAdvisorClientIdRoute,
}

const AppAdvisorRouteWithChildren = AppAdvisorRoute._addFileChildren(
  AppAdvisorRouteChildren,
)

interface AppRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBudgetRoute: typeof AppBudgetRoute
  AppChallengesRoute: typeof AppChallengesRoute
  AppCoachRoute: typeof AppCoachRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPricingRoute: typeof AppPricingRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorRoute: AppAdvisorRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBudgetRoute: AppBudgetRoute,
  AppChallengesRoute: AppChallengesRoute,
  AppCoachRoute: AppCoachRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPricingRoute: AppPricingRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
